name = "xonix-multiplayer"
main = "src/worker.ts"
compatibility_date = "2025-03-12"
assets = { directory = "./public" }
workers_dev = true

routes = [
  { pattern = "kuangkuang.top", custom_domain = true },
]

[[durable_objects.bindings]]
name = "GAME_ROOMS"
class_name = "GameRoom"

[[durable_objects.bindings]]
name = "LOBBY"
class_name = "Lobby"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom", "Lobby"]
